server:
  port: 8081
spring:
  flyway:
    enabled: true
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    locations: "classpath:db/migration"
    baseline-on-migrate: true
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    root: "INFO"
    co.com.bancolombia: "DEBUG"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    schema: "${DB_SCHEMA}"
adapter:
  restconsumer:
    timeout: 300000
    url: "http://autenticacion-service:8080"
  sqs:
    region: "us-east-2"
    notificationQueueUrl: "https://sqs.us-east-2.amazonaws.com/241636745167/loan-notification-email-queue"
    debtCapacityQueueUrl: "https://sqs.us-east-2.amazonaws.com/241636745167/debt-capacity-queue"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
security:
  jwt:
    secret: "${JWT_SECRET}"
    expiration-seconds: 5184000
    issuer: "autenticacion"
auth:
  base-url: "http://autenticacion-service:8080"
entrypoint:
  sqs:
    region: "us-east-2"
    #endpoint: "http://localhost:4566"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/241636745167/debt-capacity-reply-queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
